backend:
  name: github
  repo: Lastef60/one-click-hugo-cms

media_folder: static/content/images
public_folder: /content/images

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'content/index.md'
        label: 'Index Page'
        name: 'index'
        fields:
          - { name: 'title', label: 'Title' }
          - { name: 'content', label: 'Content', widget: 'markdown' }

      - file: 'content/galerie.md'
        label: 'Galerie Page'
        name: 'galerie'
        fields:
          - { name: 'title', label: 'Title' }
          - { name: 'content', label: 'Content', widget: 'markdown' }

      - file: 'content/tarifs.md'
        label: 'Tarif Page'
        name: 'tarif'
        fields:
          - { name: 'title', label: 'Title' }
          - { name: 'content', label: 'Content', widget: 'markdown' }

      - file: 'content/contact.md'
        label: 'Contact Page'
        name: 'contact'
        fields:
          - { name: 'title', label: 'Title' }
          - { name: 'content', label: 'Content', widget: 'markdown' }
